# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d5d0d91e007b0b1f9e7022f1732dde1a715af9a4581909c05a15a8477aba5b10aabbae4fad651fe76d603f682d96e9a7b91c0bc1b72c57aa97425bdb08ef6fc

test:
  secret_key_base: 473468f9826daa063a002118b96c3833380118e9daa9e927a66e539094a3a33b83a705353a8cea408e980eff75458ff3ce442285fa064d6da5c52c0f6bc18158

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
